steps:
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://plasma-tmp/cloud-build-spl-cargo.tgz', '/workspace/deps/cloud-build-spl-cargo.tgz']
- name: ubuntu
  args: ['/workspace/deps/unpack']
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/arjunguha-research-group/spl-deps:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/arjunguha-research-group/spl-deps:latest', '--cache-from', 'gcr.io/arjunguha-research-group/spl-deps:latest', 'deps']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/arjunguha-research-group/spl:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/arjunguha-research-group/spl-deps:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/arjunguha-research-group/spl:latest', '--cache-from', 'gcr.io/arjunguha-research-group/spl:latest', '.']
  timeout: 600s
images: ['gcr.io/arjunguha-research-group/spl-deps:latest', 'gcr.io/arjunguha-research-group/spl:latest']
artifacts:
  objects:
    location: 'gs://plasma-tmp/'
    paths: ['/workspace/deps/cloud-build-spl-cargo.tgz']