steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/arjunguha-research-group/spl:latest']
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://plasma-tmp/cloud-build-spl-cargo.tgz', '/workspace/cloud-build-spl-cargo.tgz']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'spl', '--cache-from', 'gcr.io/arjunguha-research-group/spl:latest', '.']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--name', 'spl', 'spl', '/bin/true']
- name: 'gcr.io/cloud-builders/docker'
  args: ['cp', 'spl:/root/cloud-build-spl-cargo.tgz', '/workspace/cloud-build-spl-cargo.tgz']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'spl', 'gcr.io/arjunguha-research-group/spl' ]
images: ['gcr.io/arjunguha-research-group/spl:latest']
artifacts:
  objects:
    location: 'gs://plasma-tmp/'
    paths: ['/workspace/cloud-build-spl-cargo.tgz']