steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/umass-plasma/spl:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/umass-plasma/spl:latest', '--cache-from', 'gcr.io/umass-plasma/spl:latest', '.']
  timeout: 600s
images: ['gcr.io/umass-plasma/spl:latest']
