[package]
name = "spl-lib"
version = "0.1.0"
authors = ["Arjun Guha <arjun@cs.umass.edu>"]

[dependencies]
hyper = "0.12.7"
futures = "0.1"
hyper-tls = "0.3"
serde_json = "1.0"
nom = "4.0"
rust-s3 = "0.10.0-beta.0"
chrono = "0.4.5"
http = "0.1.7"
rpds = "0.5.0"
leak = "0.1.2"
reqwest = "0.8.8"
